Lottery.Web/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Lottery.Manage.services.InfoCollector;
using Lottery.Manage.services.LotteryManage;
using Lottery.Manage.services.LotteryQuiz;
using Lottery.Models.Models.DataStorageModels.LotteryQuiz;
using Lottery.Models.Models.LotteryViewModels;
using Lottery.Models.Models.QuestionViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lottery.Web.Controllers
{
    public class QuestionController : Controller
    {
        private readonly ILotteryManageService _lotteryManageService;
        private readonly ILotteryInfoProviderService _lotteryInfoProviderService;
        private readonly ILotteryQuizService _lotteryQuizService;
        private static readonly int pageSize = 10;

        public QuestionController(ILotteryInfoProviderService lotteryInfoProviderService, ILotteryManageService lotteryManageService, ILotteryQuizService lotteryQuizService)
        {
            _lotteryInfoProviderService = lotteryInfoProviderService;
            _lotteryManageService = lotteryManageService;
            _lotteryQuizService = lotteryQuizService;
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> AllQuestion(int? page, int? size)
        {
            ViewBag.StatusMessage = StatusMessage;
            var question = await _lotteryQuizService.GetAllQuestions();
            var pageNumer = page ?? 1;
            var currentPageSize = size ?? pageSize;
            var paginatedList = new PaginatedList<Question>(question.AsQueryable(), question.Count,pageNumer,currentPageSize);
            return PartialView(paginatedList);
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> CreateQuestion(int? amountOfAnswers)
        {
            int amount = amountOfAnswers ?? 1;
            var model = new QuestionCreateViewModel() {AmountOfAnswers = amount };
            return PartialView(model);
        }


        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> CreateQuestion(QuestionCreateViewModel model)
        {
            if (!model.Answers.Any() && model.QuestionType.Equals(QuestionType.Close))
            {
                return PartialView(model);
            }
            var result = await _lotteryManageService.AddNewQuestion(model.Question, model.QuestionType, model.Answers.ToList());
            if (!result.Success)
            {
                StatusMessage = result.Description;
                return RedirectToAction(nameof(AllQuestion));
            }
            StatusMessage = "Question successfully added";
            return RedirectToAction(nameof(AllQuestion));
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> DeleteQuestion(int questionId)
        {
            var result = await _lotteryManageService.DeleteQuestion(questionId);
            if (!result.Success)
            {
                StatusMessage = result.Description;
                return RedirectToAction(nameof(AllQuestion));
            }

            StatusMessage = "question deleted";
            return RedirectToAction(nameof(AllQuestion));
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> UpdateQuestion(int questionId, int? AmountOfAnswers)
        {
            
            var question = await _lotteryQuizService.GetQuestionById(questionId);
            var model = new QuestionCreateViewModel();
            model.Question = question.Text;
            model.Answers = (await _lotteryQuizService.GetAllAnwserOnTheQuestion(question)).Select(x=>x.Text);
            model.AmountOfAnswers = AmountOfAnswers?? model.Answers.Count();
            model.Id = question.Id;
            return PartialView(model);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> UpdateQuestion(QuestionCreateViewModel model)
        {
            //var question = Mapper.Map<Question>(model);
            var question = new Question();
            question.Id = model.Id;
            question.Text = model.Question;
            var result = await _lotteryManageService.UpdateQuestion(question, model.Answers.ToList());
            if (!result.Success)
            {
                StatusMessage = result.Description;
                return RedirectToAction(nameof(AllQuestion));
            }
            
            StatusMessage = "question updated";
            return RedirectToAction(nameof(AllQuestion));
        }

        [TempData]
        public string StatusMessage { get; set; }
    }
}

Lottery.Web/Views/Question/AllQuestion.cshtml
@using Lottery.Models.Models.DataStorageModels.LotteryQuiz
@model Lottery.Models.Models.LotteryViewModels.PaginatedList<Lottery.Models.Models.DataStorageModels.LotteryQuiz.Question>
    
<h3 class="label-info">@ViewBag.StatusMessage</h3>
<p>
    <a asp-action="CreateQuestion"  data-ajax="true" data-ajax-method="get" data-ajax-update="#update">Create New</a>
</p>
<div>
    <form asp-action="AllQuestion" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
        <label class="label label-info"></label>
        <input id="size" name="size" type="number" value="@Model.PageSize"/>
        <input id="page" name="page"  value="1" type="hidden"/>
        <button type="submit" class="btn btn-default">Update</button>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Text
            </th>
            <th>
                Type
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.GetPaginatedList()) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                <a class="btn btn-info" asp-action="UpdateQuestion" asp-route-questionId="@item.Id" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">Update question</a>
            </td>
            <td>
                <a class="btn btn-info" asp-action="DeleteQuestion" asp-route-questionId="@item.Id" data-ajax="true" data-ajax-method="post" data-ajax-update="#update">Delete Question</a>
            </td>
        </tr>
    }
    </tbody>
</table>
<div class="item">
    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="AllQuestion"
       asp-route-page="@(Model.PageNumber - 1)"
       asp-route-size="@Model.PageSize"
       class="btn btn-default @prevDisabled"
       method="get"
       data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
        Previous
    </a>

    <a asp-action="AllQuestion"
       asp-route-page="@(Model.PageNumber + 1)"
       asp-route-size="@Model.PageSize"
       class="btn btn-default @nextDisabled"
       method="get"
       data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
        Next
    </a>
</div>

Lottery.Web/Views/Question/CreateQuestion.cshtml
@using Lottery.Models.Models.DataStorageModels.LotteryQuiz
@using Lottery.Models.Models.DataStorageModels.Types
@model Lottery.Models.Models.QuestionViewModel.QuestionCreateViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container">
    <div class="">
        <form asp-controller="Question" asp-action="CreateQuestion"  data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
            <div class="item form-group">
                <label asp-for="AmountOfAnswers">AmountOfAnswers</label>
                <input id="AmountOfAnswers" name="AmountOfAnswers" type="number" value="@Model.AmountOfAnswers"/>
            </div>
            <button type="submit">Update Model</button>
        </form>
      
    </div>
    <div class="">
        <form asp-controller="Question" asp-action="CreateQuestion" data-ajax="true" data-ajax-method="post" data-ajax-update="#update">
            <div class="form-control">
                <label asp-for="Question"></label>
                <input asp-for="Question" />
                <span asp-validation-for="Question"></span>
            </div>
            <div class="item form-group">
                <input asp-for="AmountOfAnswers" type="hidden" value="@Model.AmountOfAnswers"/>
            </div>
            <div class="form-control">
                <label asp-for="QuestionType"></label>
                <select asp-for="QuestionType" asp-items=@(Html.GetEnumSelectList<QuestionType>())></select>
                <span asp-validation-for="Question"></span>
            </div>
            <div>
                 <label class="label label-info">Answers</label>
                <ul class="list-group">
                    @for (int i = 0; i < Model.AmountOfAnswers; i++)
                    {
                        <li class="list-group-item"><input asp-for="Answers"/></li>
                    }
                </ul>
            </div>
            <button type="submit" class="btn btn-default">Save</button>
        </form>
    </div>
</div>

Lottery.Web/Views/Question/UpdateQuestion.cshtml
@using Lottery.Models.Models.DataStorageModels.LotteryQuiz
@model Lottery.Models.Models.QuestionViewModel.QuestionCreateViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container">
    <div class="">
        <form asp-controller="Question" asp-action="UpdateQuestion" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
                <input id="questionId" name="questionId" value="@Model.Id" type="hidden"/>
                <label asp-for="AmountOfAnswers">AmountOfAnswers</label>
                <input id="AmountOfAnswers" name="AmountOfAnswers" type="number" value="@Model.AmountOfAnswers"/>
            <button type="submit">Update Model</button>
        </form>

    </div>
    <div class="">
        <form asp-controller="Question" asp-action="UpdateQuestion" data-ajax="true" data-ajax-method="post" data-ajax-update="#update">
            <input asp-for="Id" type="hidden"/>
            <div class="form-control">
                <label asp-for="Question"></label>
                <input asp-for="Question"/>
                <span asp-validation-for="Question"></span>
            </div>
            <div class="item form-group">
                <input asp-for="AmountOfAnswers" type="hidden" value="@Model.AmountOfAnswers"/>
            </div>
            <div class="form-control">
                <label asp-for="QuestionType"></label>
                <select asp-for="QuestionType" asp-items=@(Html.GetEnumSelectList<QuestionType>())></select>
                <span asp-validation-for="Question"></span>
            </div>
            <div>
                <label class="label label-info">Answers</label>
                <ul class="list-group">
                    @for (int i = 0; i < Model.AmountOfAnswers; i++)
                    {
                        if (Model.Answers.Count() == Model.AmountOfAnswers)
                        {
                            <li class="list-group-item"><input asp-for="Answers" value="@Model.Answers.ElementAt(i)"/></li>
                        }
                        else
                        {
                            <li class="list-group-item"><input asp-for="Answers" value=""/></li>
                        }
                    }
                </ul>
            </div>
            <button type="submit" class="btn btn-default">Save</button>
        </form>
    </div>
</div>