Lottery.Web/Controllers/ExcelDataController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Lottery.Manage.services;
using Lottery.Manage.services.InfoCollector;
using Lottery.Models.Models.DataStorageModels.Lottery;
using Lottery.Models.Models.DataStorageModels.Roles;
using Lottery.Models.Models.Excel;
using Lottery.Models.Models.LotteryViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;

namespace Lottery.Web.Controllers
{
    public class ExcelDataController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IExcelDataService _excelDataService;
        private readonly ILotteryInfoProviderService _infoProviderService;
        private readonly int pageSize = 10;

        public ExcelDataController(IHostingEnvironment hostingEnvironment, IExcelDataService excelDataService, ILotteryInfoProviderService infoProviderService)
        {
            _hostingEnvironment = hostingEnvironment;
            _excelDataService = excelDataService;
            _infoProviderService = infoProviderService;
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Index(int? page, int? size)
        {
            var lotteryList = await _infoProviderService.GetAllLotteries();
            var pageNumber = page ?? 1;
            var currentPageSize = size ?? pageSize;
            var paginatedList = new PaginatedList<LotteryEntity>(lotteryList.AsQueryable(), lotteryList.Count(),
                pageNumber, currentPageSize);
            ViewBag.StatusMessage = StatusMessage;
            return PartialView(paginatedList);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ExportLotteries(LotteryFilters filter)
        {
            await _excelDataService.ExportLotteries(_hostingEnvironment.WebRootPath, filter);
            StatusMessage = $"Exported:";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> ImportLottery()
        {
            var file = Request.Form.Files[0];
            var result = await _excelDataService.ImportLottery(_hostingEnvironment.WebRootPath, file);
            StatusMessage = result.Message;
            return RedirectToAction(nameof(Index));
        }
        [TempData]
        public string StatusMessage { get; set; }
    }
}

Lottery.Web/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Lottery.Manage.services;
using Lottery.Manage.services.LotteryManage;
using Lottery.Models.Models.DataStorageModels.Picture;
using Lottery.Models.Models.LotteryViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Lottery.Web.Controllers
{
    public class PictureController : Controller
    {
        private readonly ILotteryPictureService _lotteryPictureService;
        private readonly IHostingEnvironment _appEnvironment;
        private readonly int pageSize = 10;

        public PictureController(ILotteryPictureService lotteryPictureService, IHostingEnvironment appEnvironment)
        {
            _lotteryPictureService = lotteryPictureService;
            _appEnvironment = appEnvironment;
        }


        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Index(int? page, int? size)
        {
            var pageNumber = page??1;
            var currentPageSize = size ?? pageSize;
            var allPictures = await _lotteryPictureService.GetAllPictures();
            var paginatedList = new PaginatedList<Picture>(allPictures.AsQueryable(), allPictures.Count, pageNumber,
                currentPageSize);
            ViewBag.StatusMessage = StatusMessage;
            return PartialView(paginatedList);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> AddPicture()
        {
            var pictures = Request.Form.Files;
            foreach (var picture in pictures)
            {
                var path = "/PictureFiles/" + picture.FileName;
                
                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await picture.CopyToAsync(fileStream);
                    }
               await _lotteryPictureService.AddPicture(path);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> DeletePicture(int pictureId)
        {
            var result =  await _lotteryPictureService.DeletePicture(pictureId, _appEnvironment.WebRootPath);
            if (!result.Success)
            {
                StatusMessage = result.Description;
            }
           return RedirectToAction(nameof(Index));
        }

        [TempData]
        public string StatusMessage { get; set; }
    }
}

Lottery.Web/Controllers/PrizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Lottery.Manage.services.InfoCollector;
using Lottery.Manage.services.LotteryManage;
using Lottery.Manage.services.Prize;
using Lottery.Models.Models.DataStorageModels.Prize;
using Lottery.Models.Models.LotteryViewModels;
using Lottery.Models.Models.PrizeViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lottery.Web.Controllers
{
    public class PrizeController : Controller
    {
        private readonly ILotteryManageService _lotteryManageService;
        private readonly ILotteryInfoProviderService _lotteryInfoProviderService;
        private readonly ILotteryPrizeService _lotteryPrizeService;
        private static readonly int pageSize = 10;

        public PrizeController(ILotteryManageService lotteryManageService, ILotteryInfoProviderService lotteryInfoProviderService, ILotteryPrizeService lotteryPrizeService)
        {
            _lotteryManageService = lotteryManageService;
            _lotteryInfoProviderService = lotteryInfoProviderService;
            _lotteryPrizeService = lotteryPrizeService;
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> AllPrizies(int? page, int? size)
        {
            ViewBag.StatusMessage = StatusMessage;
            var prizies = await _lotteryPrizeService.GetAllPrizeis();
            var pageNumber = page ?? 1;
            var currentPageSize = size ?? pageSize;
            var paginatedList =
                new PaginatedList<LotteryPrize>(prizies.AsQueryable(),prizies.Count,pageNumber,currentPageSize);
            ViewBag.StatusMessage = StatusMessage;
            return PartialView(paginatedList);
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public  IActionResult CreatePrize()
        {
           return PartialView(new CreatePrizeViewModel());
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> CreatePrize(CreatePrizeViewModel model)
        {
           await _lotteryManageService.AddPrize(model.Description);
            StatusMessage = "Prize successfully added";
           return RedirectToAction(nameof(AllPrizies));
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> DeletePrize(int prizeId)
        {
            var result =  await _lotteryManageService.DeletePrize(prizeId);
            if (!result.Success)
            {
                StatusMessage = result.Description;
                return RedirectToAction(nameof(AllPrizies));
            }
            StatusMessage = "prize deleted";
            return RedirectToAction(nameof(AllPrizies));
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> UpdatePrize(int prizeId)
        {
            var prize = await _lotteryPrizeService.GetPrizeById(prizeId);
            var model = Mapper.Map<CreatePrizeViewModel>(prize);
            return PartialView(model);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> UpdatePrize(CreatePrizeViewModel model)
        {
            var prize = Mapper.Map<LotteryPrize>(model);
            var result = await _lotteryManageService.UpdatePrize(prize);
            if (!result.Success)
            {
                StatusMessage = result.Description;
                return RedirectToAction(nameof(AllPrizies));
            }
            StatusMessage = "prize updated";
            return RedirectToAction(nameof(AllPrizies));
        }

        [TempData]
        public string StatusMessage { get; set; }
    }
}

Lottery.Web/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Lottery.Manage.services.InfoCollector;
using Lottery.Manage.services.LotteryManage;
using Lottery.Manage.services.LotteryQuiz;
using Lottery.Models.Models.DataStorageModels.LotteryQuiz;
using Lottery.Models.Models.LotteryViewModels;
using Lottery.Models.Models.QuizViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lottery.Web.Controllers
{
    public class QuizController : Controller
    {

        private readonly ILotteryQuizService _lotteryQuizService;
        private readonly ILotteryManageService _lotteryManageService;
        private readonly ILotteryInfoProviderService _lotteryInfoProviderService;
        private static readonly int pageSize = 10;

        public QuizController(ILotteryQuizService lotteryQuizService, ILotteryManageService lotteryManageService, ILotteryInfoProviderService lotteryInfoProviderService)
        {
            _lotteryQuizService = lotteryQuizService;
            _lotteryManageService = lotteryManageService;
            _lotteryInfoProviderService = lotteryInfoProviderService;
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> QuizForLottery(int lotteryId)
        {
            var lottery = await _lotteryInfoProviderService.GetLotteryByIdAsync(lotteryId);
            var quiz = await _lotteryQuizService.GetQuizForLottery(lottery);
            var quizQuestion = await _lotteryQuizService.GetAllQuestionForQuiz(quiz);
            var questionAnswers = await _lotteryQuizService.GetAnswersOnTheQuestion(quizQuestion);
            var model = new QuizViewModel() { Quiz = quiz, QuizQuestionses = quizQuestion, AnswersToQuestion = questionAnswers, LotteryId = lotteryId };
            return PartialView(model);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> QuizForLottery(QuizViewModel model)
        {
            if (!ModelState.IsValid) return PartialView(model);
            await _lotteryQuizService.AddAnswersOnTheQuiz(model.QuizId, User, model.Answers, model.QuizQuestionsesId,
                model.CustomAnswers);
            await _lotteryManageService.AddParticipants(User, model.LotteryId);
            StatusMessage = "Success";
            return RedirectToAction(nameof(LotteryController.Index),"Lottery");
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> AllQuizzes(int? page, int? size)
        {
            var pageNumber = page ?? 1;
            var currentPageSize = size ?? pageSize;
            var allQuizzes = await _lotteryQuizService.GetAllQuizzes();
            var paginatedList = new PaginatedList<Quiz>(allQuizzes.AsQueryable(), allQuizzes.Count, pageNumber, currentPageSize);
            ViewBag.StatusMessage = StatusMessage;
            return PartialView(paginatedList);
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> CreateQuiz(int? amountOfQuestions)
        {
            var allQuestins = await _lotteryQuizService.GetAllQuestions();
            var model = new CreateQuizViewModel {AmountOfQuestions = amountOfQuestions ?? 5,AllQuestions = allQuestins };
            return PartialView(model);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> CreateQuiz(CreateQuizViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(model);
            }
            await _lotteryQuizService.AddNewQuiz(model.Description,model.SelectedQuestion);
            StatusMessage = "Quiz created";
            return RedirectToAction(nameof(AllQuizzes));
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> UpdateQuiz(int quizId, int? amountOfQuestions)
        {
            var targetQuiz = await _lotteryQuizService.GetQuizById(quizId);
            var model = Mapper.Map < CreateQuizViewModel > (targetQuiz);
            var questionFowQuiz = await _lotteryQuizService.GetAllQuestionForQuiz(targetQuiz);
            var allQuestions = await _lotteryQuizService.GetAllQuestions();
            var allAnswers = allQuestions.Select(x => _lotteryQuizService.GetAllAnwserOnTheQuestion(x).Result);
            model.AllQuestions = allQuestions;
            model.AllAsnwers = allAnswers.ToList();
            model.SelectedQuestion = questionFowQuiz.Select(x => x.Id);
            model.AmountOfQuestions = amountOfQuestions ?? model.SelectedQuestion.Count();
            return PartialView(model);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> UpdateQuiz(CreateQuizViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(model);
            }

            var quiz = Mapper.Map<Quiz>(model);
            var result = await _lotteryQuizService.UpdateQuiz(quiz, model.SelectedQuestion);
            if (!result.Success)
            {
                StatusMessage = result.Description;
                return RedirectToAction(nameof(AllQuizzes));
            }
            StatusMessage = result.Description;
            return RedirectToAction(nameof(AllQuizzes));
        }


        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> DeleteQuiz(int quizId)
        {
            var result = await _lotteryQuizService.DeleteQuiz(quizId);
            if (!result.Success)
            {
                StatusMessage = result.Description;
                return RedirectToAction(nameof(AllQuizzes));
            }
            StatusMessage = result.Description;
            return RedirectToAction(nameof(AllQuizzes));
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<ActionResult> AddQuizToLottery(int lotteryId,int? page, int? size)
        {
            var pageNumber = page ?? 1;
            var currentPageSize = size ?? pageSize; 
            var allQuizzes = await _lotteryQuizService.GetAllQuizzes();
            var paginatedList = new PaginatedList<Quiz>(allQuizzes.AsQueryable(),allQuizzes.Count,pageNumber,currentPageSize);
            var model = new AddQuizToLotteryViewModel {LotteryId = lotteryId,PaginatedQuizList = paginatedList};
            return PartialView(model);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> AddQuizToLottery(int lotteryId, int quizId)
        {
            await _lotteryQuizService.AddQuizToLottery(lotteryId, quizId);
            return RedirectToAction(nameof(LotteryManageController.LotteryManage), "LotteryManage");
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> QuizInfo(int quizId, int page, int size)
        {
            var quiz = await _lotteryQuizService.GetQuizById(quizId);
            var model = Mapper.Map<QuizInfoViewModel>(quiz);
            model.Questions = await _lotteryQuizService.GetAllQuestionForQuiz(quiz);
            model.Lotteries = await _lotteryQuizService.GetAllLotteriesForQuiz(quiz);
            return PartialView(model);
        }

        [TempData]
        public string StatusMessage { get; set; }

    }
}

Lottery.Web/Views/Shared/_Layout.cshtml
@using Lottery.Models.Models.DataStorageModels.Roles
@using Lottery.Models.Models.DataStorageModels.User
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lottery.Web</title>
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="css/Timer.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
       
    </environment>

</head>
<body>
    <div id="globalUpdate">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar">Hi</span>
                        <span class="icon-bar">HI</span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Lottery" asp-action="MainPage" class="navbar-brand">Lottery</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Lottery" asp-action="MainPage">Home</a></li>
                        @if (User.IsInRole(Roles.Admin.ToString()) || User.IsInRole(Roles.Manager.ToString()))
                        {
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Manage
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    @if (User.IsInRole(Roles.Admin.ToString()))
                                    {
                                        <li><a asp-area="" asp-controller="Manage" asp-action="AdminManage" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">ManageView</a></li>
                                    }
                                    @if (User.IsInRole(Roles.Manager.ToString()))
                                    {
                                        <li><a asp-area="" asp-controller="LotteryManage" asp-action="LotteryManage" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">Lottery Manage</a></li>
                                        <li><a asp-area="" asp-controller="Question" asp-action="AllQuestion" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">All Questions</a></li>
                                        <li><a asp-area="" asp-controller="Prize" asp-action="AllPrizies" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">All prizies</a></li>
                                        <li><a asp-area="" asp-controller="Quiz" asp-action="AllQuizzes" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">All quizzes</a></li>
                                        <li><a asp-area="" asp-controller="Picture" asp-action="Index" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">All pictures</a></li>
                                        <li><a asp-area="" asp-controller="ExcelData" asp-action="Index" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">Excel</a></li>
                                    }
                                </ul>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li><a asp-area="" asp-controller="Lottery" asp-action="AllResults" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">Held lotteries</a></li>
                        }
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - Lottery.Web</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
            <script src="~/js/utils.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>