Lottery.Web/Controllers/LotteryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Lottery.Manage.services.InfoCollector;
using Lottery.Manage.services.LotteryManage;
using Lottery.Manage.services.Prize;
using Lottery.Models.Models.DataStorageModels.Lottery;
using Lottery.Models.Models.DataStorageModels.LotteryParticipants;
using Lottery.Models.Models.DataStorageModels.LotteryWiner;
using Lottery.Models.Models.DataStorageModels.Prize;
using Lottery.Models.Models.LotteryViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Lottery.Web.Controllers
{
    [Authorize]
    public class LotteryController : Controller
    {
        private readonly ILotteryManageService _lotteryManageService;
        private readonly ILotteryInfoProviderService _lotteryInfoProviderService;
        private readonly ILotteryPrizeService _lotteryPrizeService;
        private static readonly int pageSize = 10;

        public LotteryController(ILotteryManageService lotteryManageService, ILotteryInfoProviderService lotteryInfoProviderService, ILotteryPrizeService lotteryPrizeService)
        {
            _lotteryManageService = lotteryManageService;
            _lotteryInfoProviderService = lotteryInfoProviderService;
            _lotteryPrizeService = lotteryPrizeService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> MainPage()
        {
            var futureLotteries = await _lotteryInfoProviderService.GetFutureLotteries(); 
            var paginatedList = new PaginatedList<LotteryEntity>(futureLotteries.AsQueryable(),futureLotteries.Count(),1,pageSize);
            var closestLottery = await _lotteryInfoProviderService.GetClosestLotteryForUser(User);
            var lastLottery = await _lotteryInfoProviderService.GetLastLottery();
            var closestLotteryParticipants = closestLottery == null ? new List<LotteryParticipants>(): await _lotteryInfoProviderService.GetLotteryParticipants(closestLottery.Id);
            var closestLotteryPartisipantsPaginated = new PaginatedList<LotteryParticipants>(closestLotteryParticipants.AsQueryable(), closestLotteryParticipants.Count, 1, pageSize);
            var model = new LotteryListViewModel(closestLottery, paginatedList, lastLottery, closestLotteryPartisipantsPaginated, StatusMessage) ;
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ClosestLottery()
        {
            var closestLottery = await _lotteryInfoProviderService.GetClosestLottery();
            return PartialView(closestLottery);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index(int? page,int? size)
        {
            var futureLotteries = await _lotteryInfoProviderService.GetFutureLotteries();
            var closestLottery = await _lotteryInfoProviderService.GetClosestLotteryForUser(User);
            var lastLottery = await _lotteryInfoProviderService.GetLastLottery();
            var pageNumber = page ?? 1;
            var currentPageSize = size ?? pageSize;
            var closestLotteryParticipants = await _lotteryInfoProviderService.GetLotteryParticipants(closestLottery.Id);
            var closestLotteryPartisipantsPaginated = new PaginatedList<LotteryParticipants>(closestLotteryParticipants.AsQueryable(),closestLotteryParticipants.Count,1,closestLotteryParticipants.Count==0?1: closestLotteryParticipants.Count);
            var paginatedList = new PaginatedList<LotteryEntity>(futureLotteries.AsQueryable(), futureLotteries.Count(), pageNumber,currentPageSize);
            var model = new LotteryListViewModel(closestLottery, paginatedList, lastLottery,closestLotteryPartisipantsPaginated, StatusMessage);
            return PartialView(model);
        }

        [HttpGet]
        [Authorize(Roles = "User,Manager")]
        public async Task<IActionResult> LotteryResult(int lotteryId)
        {
            var lottery = await _lotteryInfoProviderService.GetLotteryByIdAsync(lotteryId);
            var isUserWinner = await _lotteryInfoProviderService.IsUserWinner(User, lottery);
            var place = await _lotteryInfoProviderService.GetWinnerPlace(User, lottery);
            var allParticipants = await _lotteryInfoProviderService.GetLotteryParticipants(lotteryId);
            var lotteryWinners = await _lotteryInfoProviderService.GetAllLotteryWinners(lotteryId);
            var prize = place==0 ? new LotteryPrize() : await _lotteryPrizeService.GetPrizeForPlace(lottery, place);
            var model = new LotteryResultViewModel(){Lottery = lottery,IsUserWinner = isUserWinner, Place = place ,Prize = prize,LotteryParticipants = allParticipants,LotteryWinners = lotteryWinners};
            return PartialView(model);
        }

        [HttpGet]
        [Authorize(Roles = "User,Manager")]
        public async Task<IActionResult> AllResults(LotteryFilters filter)
        {
            if (filter.Page == 0)
            {
                filter.Page = 1;
                filter.LeftDate = DateTime.MinValue;
                filter.RightDate = DateTime.Now;
                filter.PageSize = pageSize;
            }
            var heldLotteryList = await _lotteryInfoProviderService.GetAllHeldLotteries(filter);
            var pageNumber = filter.Page;
            var currentPageSize = filter.PageSize;
            var paginatedList = new PaginatedList<LotteryEntity>(heldLotteryList.OrderByDescending(x => x.LotteryDate).AsQueryable(), heldLotteryList.Count(), pageNumber,Math.Abs(currentPageSize));
            filter.PaginatedList = paginatedList;
            return PartialView(filter);
        }

        [HttpPost]
        [Authorize(Roles = "User,Manager")]
        public async Task<IActionResult> AddParticapants(int lotteryId)
        {
            if (! await _lotteryInfoProviderService.IsAlreadyRegisteredOnTheLottery(lotteryId, User) && ! await _lotteryInfoProviderService.IsUserExcludeFromLottery(User,lotteryId))
            {
                var validationResult = await _lotteryManageService.CheckUserForLottery(User, lotteryId);
                if (validationResult.Success)
                {
                    if (await _lotteryInfoProviderService.IsLotteryHasQuiz(lotteryId))
                        return RedirectToAction(nameof(QuizController.QuizForLottery), "Quiz",
                            new {lotteryId = lotteryId});
                    await _lotteryManageService.AddParticipants(User, lotteryId);
                    StatusMessage = "Success";
                    return RedirectToAction(nameof(Index));
                }
                StatusMessage = validationResult.Description;
                return RedirectToAction(nameof(Index));
            }
            StatusMessage = "you already registered on this lottery";
            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        [Authorize(Roles = "User,Manager")]
        public async Task<string> LastLotteryWinners()
        {
            var lastHeldLottery = await _lotteryInfoProviderService.GetLastHeldLottery();
            Thread.Sleep(lastHeldLottery.Delay*1000);
            return  JsonConvert.SerializeObject(_lotteryInfoProviderService.GetAllLotteryWinners(lastHeldLottery.Id).Result.Select(x=>string.Format("Place {0} is {1}",x.Place, x.ApplicationUser.UserName)));
        }
        [TempData]
        public string StatusMessage { get; set; }
    }
}

Lottery.Web/Views/Lottery/AllResults.cshtml
@using Lottery.Models.Models.LotteryViewModels
@model Lottery.Models.Models.LotteryViewModels.LotteryFilters
    
<div>
    <div class="item">
        <form asp-controller="Lottery" asp-action="AllResults" method="get"
              data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
            <div class="form-control">
                <label asp-for="LeftDate">After date</label>
                <input asp-for="LeftDate" type="datetime-local"/>
                <label asp-for="RightDate">Before Date</label>
                <input asp-for="RightDate"   type="datetime-local"/>
            </div>
            <div class="form-control">
                <label asp-for="AmountOfWinnersMin">Min Amount of Winners</label>
                <input type="number" asp-for="AmountOfWinnersMin" value="@Model.AmountOfWinnersMin"/>
                <label asp-for="AmountOfWinnersMax">Max amount of winners</label>
                <input type="number"asp-for="AmountOfWinnersMax" value="@Model.AmountOfWinnersMax"/>
            </div>
            <div>
                <input asp-for="Page" value="@Model.Page" type="hidden"/>
            </div>
            <div>
                <label asp-for="PageSize" class="label label-info"></label>
                <input asp-for="PageSize" />
            </div>
            <button type="submit">filter</button>
        </form>
    </div>
   
    <table class="table">
        <thead>
        <tr>
            <th>Lottery description</th>
            <th>Lottery Date</th>
            <th>Amount of winners</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.PaginatedList.GetPaginatedList())
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LotteryDate)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.AmountOfWinners)
                </td>
                <td>
                    <a class="action-link" asp-controller="Lottery" asp-route-lotteryId="@item.Id" asp-action="LotteryResult"data-ajax="true" data-ajax-method="get" data-ajax-update="#update">Results</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <div class="item">
        @{
            var prevDisabled = !Model.PaginatedList.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.PaginatedList.HasNextPage ? "disabled" : "";
        }

        <form asp-action="AllResults" class="btn btn-default @prevDisabled" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
            <div>
                <input asp-for="LeftDate" type="hidden" />
                <input asp-for="RightDate" type="hidden"/>
            </div>
            <div>
                <input type="hidden" asp-for="AmountOfWinnersMin" value="@Model.AmountOfWinnersMin" />
                <input type="hidden"asp-for="AmountOfWinnersMax" value="@Model.AmountOfWinnersMax"/>
            </div>
            <div>
                <input asp-for="Page" value="@(Model.Page-1)" type="hidden"/>
            </div>
            <div>
                <input asp-for="PageSize" type="hidden" />
            </div>
            <button type="submit">Previous</button>
        </form>

        <form asp-action="AllResults" class="btn btn-default @nextDisabled" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
            <div>
                <input asp-for="LeftDate"  type="hidden" />
                <input asp-for="RightDate" va type="hidden" />
            </div>
            <div>
                <input type="hidden" asp-for="AmountOfWinnersMin" value="@Model.AmountOfWinnersMin" />
                <input type="hidden" asp-for="AmountOfWinnersMax" value="@Model.AmountOfWinnersMax" />
            </div>
            <div>
                <input asp-for="Page" value="@(Model.Page+1)" type="hidden" />
            </div>
            <div>
                <input asp-for="PageSize"  type="hidden"/>
            </div>
            <button type="submit">Next</button>
        </form>
    </div>
</div>

Lottery.Web/Views/Lottery/Animation.cshtml
<div>
   
</div>

Lottery.Web/Views/Lottery/ClosestLottery.cshtml
@model Lottery.Models.Models.DataStorageModels.Lottery.LotteryEntity
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var time = @Model.LotteryDate.Subtract(DateTime.Now);
    var minutes = time.TotalMinutes;
}
<div class="item" id="refreshTimer">
    @if (time.TotalMinutes > 0 && time.TotalMinutes < 5)
    {
        <div class="container">
            <div id="timer">
                <label for="hour">Hours </label>
                <div id="hour">@Math.Floor(time.TotalHours)</div>
                <label for="minute">Minutes</label>
                <div id="minute">@time.Minutes</div>
                <label for="second">Seconds</label>
                <div id="second">@time.Seconds</div>
            </div>
        </div>
    }
</div>
@if (time.TotalMinutes > 0 && time.TotalMinutes < 5)
{
    <div>
        <img src="@Model.Picture?.Pass" class="img-circle"/>
    </div>
}
<script>
    //window.onload = refreshTimer();
    //window.onload = timer();
</script>

Lottery.Web/Views/Lottery/Index.cshtml
@model Lottery.Models.Models.LotteryViewModels.LotteryListViewModel
@using System.Diagnostics
@using Lottery.Models.Models.DataStorageModels.Lottery
@using Lottery.Models.Models.DataStorageModels.Roles
@using Lottery.Models.Models.DataStorageModels.Types

<div class="container-fluid" id="update">
    <div id="trigger"></div>
    <div class="col-sm-4">
        @if (User.IsInRole(Roles.Manager.ToString()) || User.IsInRole(Roles.User.ToString()))
        {
            <div class="item">
                @Html.Partial("ClosestLottery", Model.ClosestLottery ?? new LotteryEntity())
            </div>
        }
        <div class="item" id="showWinners">
            <table class="table table-bordered" id="Table">
                <tr></tr>
            </table>
        </div>
        @if ((User.IsInRole(Roles.User.ToString()) || User.IsInRole(Roles.Manager.ToString())) && Model.LastHeldLottery?.LotteryDate.Subtract(DateTime.Now).TotalSeconds < Model.LastHeldLottery?.Delay)
        {
            <div class="item">
                <label class="label label-info"> Results of last held lottery </label>
                <a class="action-link" asp-controller="Lottery" asp-route-lotteryId="@Model.LastHeldLottery.Id" asp-action="LotteryResult" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">Results</a>
            </div>
        }
        <div class="item">
            <form asp-controller="Lottery" asp-action="Index" method="get"
                  data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
                <label for="size" class="label label-info">Page Size</label>
                <input id="size" name="size" type="number" value="@Model.PaginadeFutureLotteryList.PageSize" />
                <button type="submit">Update</button>
            </form>
        </div>
        <div class="item">
            <div class="item">
                <form asp-controller="Lottery" asp-action=""></form>
            </div>
            <h1 class="warning">@Model.StatusMessage</h1>
            <div class="container">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Lottery</th>
                            <th>RegistrationEndDate</th>
                            <th>Lottery Date</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var lottery in Model.PaginadeFutureLotteryList.GetPaginatedList())
                        {
                            <tr>
                                <td>
                                    @lottery.Description
                                </td>
                                <td>
                                    @lottery.RegistrationEndDate
                                </td>
                                <td>
                                    @lottery.LotteryDate
                                </td>
                                @if (User.IsInRole(Roles.User.ToString()) || User.IsInRole(Roles.Manager.ToString()) && lottery.LotteryType != LotteryType.Close)
                                {
                                    <td>
                                        <a asp-controller="Lottery" asp-action="AddParticapants" asp-route-lotteryId="@lottery.Id" data-ajax="true" data-ajax-method="post" data-ajax-update="#update"> Take Part</a>
                                    </td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
    <div class="">
        @{
            var prevDisabled = !Model.PaginadeFutureLotteryList.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.PaginadeFutureLotteryList.HasNextPage ? "disabled" : "";
        }

        <a asp-action="Index"
           asp-route-page="@(Model.PaginadeFutureLotteryList.PageNumber - 1)"
           asp-route-size="@Model.PaginadeFutureLotteryList.PageSize"
           class="btn btn-default @prevDisabled"
           method="get"
           data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
            Previous
        </a>

        <a asp-action="Index"
           asp-route-page="@(Model.PaginadeFutureLotteryList.PageNumber + 1)"
           asp-route-size="@Model.PaginadeFutureLotteryList.PageSize"
           class="btn btn-default @nextDisabled"
           method="get"
           data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
            Next
        </a>
    </div>

@if (User.IsInRole("Manager"))
{
    <div id="updateParticipants">
        @if (Model.ClosestLottery != null && Model.ClosestLottery.LotteryDate.Subtract(DateTime.Now).TotalMinutes < 5)
        {
            <div class="item">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Partisipants User Name</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var participants in Model.ClosestLotteryParticipants.GetPaginatedList())
                    {
                        <tr>
                            <td>
                                @participants.Participants.UserName
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        }
    </div>
}

Lottery.Web/Views/Lottery/LotteryResult.cshtml
@using Lottery.Models.Models.DataStorageModels.Roles
@model Lottery.Models.Models.LotteryViewModels.LotteryResultViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container">
    <table class="table-condensed">
        <thead>
        <tr>
            <th>Lottery description</th>
            <th>amount of winners</th>
            <th>amount of participants </th>
            <th>Winner</th>
            <th>Prize</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>@Model.Lottery.Description</td>
            <td>@Model.Lottery.AmountOfWinners</td>
            <td>@Model.LotteryParticipants.Count()</td>
            @if (Model.IsUserWinner)
            {
                <td class="success">You are winner, your place is: @Model.Place</td>
            }
            else
            {
                <td>Nope</td>
            }
            <td>@Model.Prize?.Description</td>
        </tr>
        </tbody>
    </table>
    @if (User.IsInRole(Roles.Manager.ToString()))
    {
        <table class="table-condensed">
            <thead>
            <tr>
                <th>UserName</th>
                <th>isWinner</th>
            </tr>
            </thead>
            <tbody>
         
                @for (int i = 0; i < Model.LotteryParticipants.Count(); i++)
                {
                    <tr>
                    <td>@Model.LotteryParticipants.ElementAt(i).Participants.UserName</td>
                   @if (Model.LotteryWinners.Any(x => x.ApplicationUser.Equals(Model.LotteryParticipants.ElementAt(i).Participants)))
                     {
                         <td> <label class="label label-success">winner</label></td>
                     }
                     else
                     {
                         <td>Nope</td>
                     }
                    </tr>
                }
         
            </tbody>
        </table>
    }
    <a class="btn btn-link center-block" asp-action="Index" method="get"data-ajax="true" data-ajax-method="get" data-ajax-update="#update">Back</a>
</div>

Lottery.Web/Views/Lottery/MainPage.cshtml
@model Lottery.Models.Models.LotteryViewModels.LotteryListViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container" id="update">
    @Html.Partial("Index",@Model)
</div>

Lottery.Web/Views/Lottery/Success.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if (ViewBag.Success.Equals(true))
{
    <h1 class="success">Operration successfully</h1>
}
else
{
    <h1 class="danger">Operation failed</h1>
}